### ISSUE TITLE
Retrieve all block children

### ISSUE THREAD

**Issue by dyllan-to-you** [souvikinator/notion-to-md#13]
Hi! I noticed that you currently support passing `totalPage` to specify the number of pages/blocks that it requests from the API (thanks to #9 )

What about supporting `totalPage = null`, which would automatically attempts to retrieve all block children instead of a fixed number of pages? It would simplify usecases where you may not know the number of blocks there are on the page beforehand but you always know you want all of them. 

If you're open to such a PR I could write and submit one!

**Comment by souvikinator** [comment]
Hey there @dyllan-to-yu 
That makes sense, let's give it a try. I'd be glad to receive a PR.

**Comment by souvikinator** [comment]
@dyllan-to-you Thanks for the contribution. Really appreciate it :)
