### ISSUE TITLE
Incorrect syntax for the orderest lists.

### ISSUE THREAD

**Issue by ShubhamVerma1811** [souvikinator/notion-to-md#18]
Hey,
 For the ordered lists (numbered_list_item) , the incorrect syntax for unordered lists (bulleted_list_item) is rendered.

Expected:
```md
1. Hey
2. There
```

Actual:
```md
- Hey
- There
```

I have tried an approach that might be able to solve this issue #19. Happy to discuss on it.

**Comment by hrithwikbharadwaj** [comment]
Even I am having the same issue,  is this fixed ?

**Comment by ShubhamVerma1811** [comment]
> Even I am having the same issue,  is this fixed ?

It's not fixed.
I am not getting enough time to work on this PR.

I'll be glad if someone can take it up.

**Comment by souvikinator** [comment]
@hrithwikbharadwaj yes, this one is on hold because of some issues with the nested numbering. I'll try to fix the issue and release an update.

**Comment by souvikinator** [comment]
@ShubhamVerma1811 No issues. I'll try to comeup with a solution. Thanks for the input so far :+1:

**Comment by raphtlw** [comment]
This can be achieved by checking if block.has_children === true.

**Comment by raphtlw** [comment]
I'm currently fixing this issue. Will make a pull request soon.

**Comment by raphtlw** [comment]
I've fixed this issue, please take a look at #35 and do let me know if you guys have any feedback on code style, etc.

**Comment by souvikinator** [comment]
Hey thanks for the contribution. I'll review the code and let you know

**Comment by souvikinator** [comment]
This issue is fixed now in the latest release, v2.4.1
Thanks to everyone for the contribution :))
