### ISSUE TITLE
Should a notion link parse to normal hyper link?

### ISSUE THREAD

**Issue by 2nthony** [souvikinator/notion-to-md#27]
![image](https://user-images.githubusercontent.com/19513289/158050393-aefc15ae-3b84-467c-b210-1f67d53f4dc4.png)

I am expect it to be `notion.so/{pageid}`

https://github.com/souvikinator/notion-to-md/blob/6608761a36879fb962adf3afccbdbd0da65b0dd1/src/notion-to-md.ts#L170-L178

Maybe in this case to handle, if the url starts with `notion` then transform to `notion.so/{pageid}`

**Comment by souvikinator** [comment]
Hey there,
Can you be specific on how to reproduce this? I never came across notion URLs starting with `notion://`

**Comment by 2nthony** [comment]
I can't reproduce this. Close this for now 🤔
