### ISSUE TITLE
feat: support text color

### ISSUE THREAD

**Issue by 2nthony** [souvikinator/notion-to-md#28]
https://github.com/2nthony/blogkit/blob/36858ff64a13508d85fd33110ccc4499675c71d0/packages/blogkit-notion/src/notion-to-md.ts#L26-L37

I override the `annotatePlainText` to support text color.

**Do you have a plan to let it extensible?**

## Showcase

Rendered HTML

![image](https://user-images.githubusercontent.com/19513289/158071489-1095da85-afab-426d-91cc-78ea1ee5bb58.png)

In notion

![image](https://user-images.githubusercontent.com/19513289/158071546-e5281657-98f0-4283-a7cd-8de5bd8b576c.png)

**Comment by souvikinator** [comment]
No plans for now as markdown doesn't support coloring. For that probably have to use HTML.

**Comment by 2nthony** [comment]
OK for that, just expect has an API to extend it. Thanks.
