### ISSUE TITLE
page in markdown

### ISSUE THREAD

**Issue by chrisyang2003** [souvikinator/notion-to-md#33]
hi, i wanna ask that can i get the page_id in the pageblock not the link_to_page block? 
![I3_MXG3GYR QJ7~I3GV`JUL](https://user-images.githubusercontent.com/63803385/174353468-ab18399c-4abc-4ec4-8800-2fe298d5083a.png)

**Comment by chrisyang2003** [comment]
I am exploring the possibility of notion + hugo, I want to automatically push my articles to my hugo blog when I only want to use notion

**Comment by souvikinator** [comment]
Can you elaborate how do want the response to be? Like do you want page ids as well in the markdown output?

**Comment by chrisyang2003** [comment]
> 

yeah，how about like the as same as the link_to_page you code '[link_to_page](xxxx)‘?

**Comment by souvikinator** [comment]
This feature is available in the latest version (`v2.4.0`)
