### ISSUE TITLE
Support for collapsible content?

### ISSUE THREAD

**Issue by dotansimha** [souvikinator/notion-to-md#36]
first, thank you for a great library! 

Seems like the following Notion content: 
<img width="450" alt="image" src="https://user-images.githubusercontent.com/3680083/175335132-f8a0811b-556b-462b-bd96-dcabdd6423bc.png">

Is being evaluated as: 
<img width="909" alt="image" src="https://user-images.githubusercontent.com/3680083/175335252-df0e34a3-a26e-4fa2-9797-c969cdd9dd03.png">

I guess in such cases, we can use the `<details>`, for example: https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab

**Comment by souvikinator** [comment]
Hey there,
Thanks for reporting. Seems like a quick task to do. 
Should be available in the next release.

**Comment by souvikinator** [comment]
Alright, so quick update. I have implemented the logic and it looks something like this:

Notion:

<img width="480" alt="image" src="https://user-images.githubusercontent.com/64456160/175538656-c8ddeccc-c8dc-4b4f-b10b-5628f88d6d1c.png">


Result: 

<img width="722" alt="image" src="https://user-images.githubusercontent.com/64456160/175538563-626162f3-d9ba-40db-a0fd-bda9950ad728.png">


However there are few limitations one must be aware of. One cannot use annotations in the toggle text.

**Comment by souvikinator** [comment]
This feature is available in the latest version (`v2.4.0`)

**Comment by dotansimha** [comment]
Amazing! thank you so much!
