### ISSUE TITLE
Lists are created with an extra empty line between rows

### ISSUE THREAD

**Issue by dotansimha** [souvikinator/notion-to-md#41]
Hi @souvikinator :)

We noticed an issue with the output of lists. We have the following Notion page (public): 
https://www.notion.so/Roadmap-232f99f86aa34383bac5d72e53aa24b7

This is how it looks like on Notion:
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/3680083/177700473-61184c34-d3df-4995-9ec0-6f57582ffd65.png">

We are converting the Notion page to Markdown and then publish it to GitHub as issue/discussion, and this is the result: https://github.com/dotansimha/graphql-yoga/issues/1358

<img width="813" alt="image" src="https://user-images.githubusercontent.com/3680083/177700545-9d2f424e-1219-4366-b9c2-4dbfc119d5af.png">

It seems like there is an additional line break between list rows:

<img width="847" alt="image" src="https://user-images.githubusercontent.com/3680083/177700671-bfdca00b-10e0-4416-a30f-ba0a9e54b792.png">

**Comment by souvikinator** [comment]
Yep! I can reproduce it. Will fix the issue and create a release shortly.
Thanks for reporting.

**Comment by dotansimha** [comment]
Thank you! I saw you bumped to 2.5.1 but release is not yet on npm?

**Comment by souvikinator** [comment]
Yes! now it's live on NPM as well. 
Thanks for the contribution :))

**Comment by souvikinator** [comment]
Closing the issue. Make sure to reopen this if the issue still persists.
