### ISSUE TITLE
"plain text" code block convertion problem

### ISSUE THREAD

**Issue by adehghanzadeh** [souvikinator/notion-to-md#47]
Hi

`plain text` code parts converted to

```
```plain text
```
instead of
```
```text
```
not supported in jekyll

```text
it is text
```

```plain text
it is plain text
```

![image](https://user-images.githubusercontent.com/86428901/181935556-25e2ac8f-f46c-448f-a96e-7fd49733a7b8.png)

For instence, I created this blog post: https://adehghanzadeh.github.io/Jekyll_minimal-mistake/try-to-deploy-this-blog-to-cloudflare-pages/

**Comment by souvikinator** [comment]
With markdown, both `plain text` and `text` works. So it's  jekyll's issue. However it doesn't seem to cause an issue in the vanilla markdown, so I can switch from `plain text` to `text`.

**Comment by souvikinator** [comment]
The changes are live in `v2.5.4`.
