### ISSUE TITLE
Support of Table of Contents

### ISSUE THREAD

**Issue by hrithwikbharadwaj** [souvikinator/notion-to-md#49]
Is there a possibility to make a Table of Contents from notion work?

I am using notion-to-md for my blog and wanted to see what can be done

**Comment by souvikinator** [comment]
Not sure how the package processess the table of contents however table of contents is similar to list of links. 
We can return table of contents as links so that they can be used as the user wants.

your thoughts?

**Comment by hrithwikbharadwaj** [comment]
Figured out a way to do this if the usecase is for blogs. Users can use something like rehype toc to convert the mdnString to a TOC or write a custom function.

For now, I wrote a Custom Function since rehype is not that flexible with styling and other things like being sticky after the scroll. 

I think there is no support needed from notion-to-md
