### ISSUE TITLE
Suggestion: Add default return value in setCustomTransformer callback function

### ISSUE THREAD

**Issue by m4rrc0** [souvikinator/notion-to-md#50]
Hi.
When using `setCustomTransformer`, we may want to transform the output only in some situations. It would be great to be able to return the default n2m output when we need to.

Exemple of what it may look like:
```
n2m.setCustomTransformer("paragraph", async (block, defaultOutput) => {
  if (hasSomeProperty(block)) return someOutput(block);
  return defaultOutput(block);
});
```

Additionally, we may want to only slightly transform the default output and it may make things easier to generate that output string then transform it.

**Comment by kungpaogao** [comment]
I would like to try looking into this. For this I see two approaches:

1. as you suggested, make the callback type have two parameters, one of which is the function for the original transformer
2. return `false`/`null` to return default value, which is similar to the approach that [marked](https://marked.js.org/using_pro#renderer) takes

What are your thoughts on this?

**Comment by kungpaogao** [comment]
I haven't started yet, but now that you've commented on it, I can start looking into it!

**Comment by souvikinator** [comment]
Hey @kungpaogao any update on this?

**Comment by kungpaogao** [comment]
@souvikinator sorry for the late reply, i implemented it here, but haven't gotten around to testing it: https://github.com/kungpaogao/notion-to-md/tree/kungpaogao/custom-transformer-default
