### ISSUE TITLE
Behaviour for uploaded images?

### ISSUE THREAD

**Issue by ashutoshsaboo** [souvikinator/notion-to-md#55]
I was seeing that for images that are added to Notion via a public url are exported as is with the same url in markdown. For custom/actually uploaded images (non publicly hosted images; from the notion filepicker/drag and drop) to Notion, how does the export work? 

Does it extract the image as base64 in markdown? Or how does it work? @souvikinator

**Comment by souvikinator** [comment]
As of now the multimedia selected from the file picker or drag and drop, the exact local path gets added.

**Comment by souvikinator** [comment]
PR #81 address this issue. Expect it to go live in the next major update, along with various bug fixes. 

Appreciate everyone's contribution in enhancing the package. :rocket:
Thank you.

**Comment by ashutoshsaboo** [comment]
Thanks for the update! @souvikinator 🚀
