### ISSUE TITLE
link containing  <> brackets breaks the library

### ISSUE THREAD

**Issue by GorvGoyl** [souvikinator/notion-to-md#56]
parsing this will throw an error: [<style>](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM#styling_the_shadow_dom)

**Comment by souvikinator** [comment]
Hey, thanks for reporting. Can you be more specific about what the error is?

**Comment by GorvGoyl** [comment]
if a notion page has a link surrounded with angular brackets, the library will throw error. screenshot of Notion page:

![screenshot 2022-12-19 at 16 13 57@2x](https://user-images.githubusercontent.com/7106086/208390112-873c7883-5ca9-4c07-bb65-89890ba0aa3f.png)

**Comment by souvikinator** [comment]
I tested it locally and the generated markdown looks like so:

![image](https://user-images.githubusercontent.com/64456160/208425316-5175729a-4cdc-4051-8884-e8a45b2b25c5.png)

however, it won't render the link which is a problem with the markdown parser and now this library.
