### ISSUE TITLE
"Could not find block" error

### ISSUE THREAD

**Issue by t3db0t** [souvikinator/notion-to-md#59]
I'm using the first example from the readme to get the markdown from a page. I have added the integration to the relevant page and copied the page ID (correctly) from the page. However, when I run the script, I get a 404 "Could not find block" error for a _different_ page ID. I have no idea why this is happening. Am I missing something? What can I do to debug this?

Code:
```js
const { Client } = require("@notionhq/client");
const { NotionToMarkdown } = require("notion-to-md");
const fs = require('node:fs/promises');

const TOKEN = process.env.TOKEN;

const notion = new Client({
  auth: TOKEN,
});

// passing notion client to the option
const n2m = new NotionToMarkdown({ notionClient: notion });

(async () => {
  const mdblocks = await n2m.pageToMarkdown("d82b628c-e95a-4723-82fc-67aaec962db9");
  const mdString = n2m.toMarkdownString(mdblocks);

  //writing to file
  fs.writeFile("test.md", mdString, (err) => {
    console.log(err);
  });
})();
```

Error:
```
@notionhq/client warn: request fail {
  code: 'object_not_found',
  message: 'Could not find block with ID: dfc6d411-0a31-45d6-ba51-be5ea4be0cf5. Make sure the relevant pages and databases are shared with your integration.'
}
```

**Note that the block ID in the error is different than what I am supplying in my script.**

**Comment by souvikinator** [comment]
Can you share how your notion page looks like?

**Comment by t3db0t** [comment]
This is the page I'm trying to render to markdown: https://t3db0t.notion.site/Sentients-Core-Rulebook-d82b628ce95a472382fc67aaec962db9

**Comment by t3db0t** [comment]
After a bunch of debugging, it appears that the parent of the block that's giving the 404 is a `synced_block` so maybe the child or parent doesn't have the right permissions.

**Comment by t3db0t** [comment]
I removed the synced page and I'm not getting the error anymore so I'll go ahead and close this
