### ISSUE TITLE
Detailed walkthrough?

### ISSUE THREAD

**Issue by kerim** [souvikinator/notion-to-md#69]
Is there a walkthrough or tutorial somewhere that offers step-by-step instructions on how to use this? Thanks!

**Comment by kerim** [comment]
What I've figured out so far:

Install:

npm install @notionhq/client
npm i notion-to-md@latest

Create Custom Integration:
https://www.notion.so/my-integrations (Copy API key created in this step.)
Open workspace in browser (doesn't work on mac app), and add integration to workspace from menu.

Now what? I know it has something to do with the javascript code in the readme, and that I need to put the API key into that, but I'm not sure how to do this?

**Comment by souvikinator** [comment]
As of now, the README is the only detailed usage guide. 
Yep that's right here are the steps as you mentioned:

1. Install dependencies:
``` 
npm install @notionhq/client
npm i notion-to-md@latest
```

2. Create Custom Integration: [notion.so/my-integrations](https://www.notion.so/my-integrations) (Copy API key created in this step.)
3. Add integration to the workspace from the menu.
4. Use API key with notion-to-md like so:
```javascript
const notion = new Client({
  auth: "your API key",
});
```
5. Copy the target page link from here:
![image](https://user-images.githubusercontent.com/64456160/232270745-c57ca196-3ebc-4cb7-842a-d4123c2e5dce.png)

Get the target page id from the link:
![image](https://user-images.githubusercontent.com/64456160/232271330-301861e3-9744-4513-bce8-1df3894fdb9f.png)

6. Use the page id here:
```javascript
const mdblocks = await n2m.pageToMarkdown("target_page_id");
```

rest of the code you can get from the README.

**Comment by kerim** [comment]
Thanks. But how do I run the code? What is the process? It looks like javascript, but I don't know how to run that from the terminal - I usually run that only within HTML web pages. (Sorry, I'm not very experienced at this...)

**Comment by souvikinator** [comment]
Ah so first you need to install `nodejs` on your computer. Once it's done just run the code like so:
```bash
node your_script.js
```
Don't be sorry, it's absolutely fine to seek help :))

**Comment by kerim** [comment]
Great. I was able to run the code, but got an error. I will open a separate issue for that.
