### ISSUE TITLE
fs.writeFile failing

### ISSUE THREAD

**Issue by kerim** [souvikinator/notion-to-md#70]
I am trying the code from the README. I added the API code and the page ID, saved it as notion-to-md.js and ran it using node.  But I get the following error:

```
node notion-to-md.js
/Users/[user folder]/Downloads/notion-to-md.js:18
  fs.writeFile("test.md", mdString, (err) => {
  ^

ReferenceError: fs is not defined
    at /Users/[user folder]/Downloads/notion-to-md.js:18:3
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.9.0

```

I tried manually creating a file called test.md, but that didn't help - same error.

**Comment by souvikinator** [comment]
you have to import fs module like so:
```javascript
const fs = require('fs');
```

**Comment by kerim** [comment]
It worked! Thanks
