### ISSUE TITLE
Unified way to handle links

### ISSUE THREAD

**Issue by Radiergummi** [souvikinator/notion-to-md#75]
I'm struggling with inline links to other pages in Notion content. Contrary to what one might expect, those aren't reported as `link_to_page`, but will silently be passed to `md.link()`:
```ts
if (content["href"])
  plain_text = md.link(plain_text, content["href"]);

parsedData += plain_text;
```
See [/src/notion-to-md.ts#L398-L401](https://github.com/souvikinator/notion-to-md/blob/5d8e213406b74b6c3a46d1a9cc9fc4d6936ca91d/src/notion-to-md.ts#L398-L401)

In this case, `href` might be `/fae18db43ae240bbb05771a6e531b494`, which makes it hard to detect valid links and replace them with references to the local pages.

A good solution would be to pass those to some kind of (new?) `link` transformer, if available.

**Comment by souvikinator** [comment]
Currently saving child pages as a separate file is a work in progress (#71). I hope that'll fix this issue.

**Comment by souvikinator** [comment]
The feature is now live in v2.6.0. Does it solve the issue?
