### ISSUE TITLE
fs dependency issues

### ISSUE THREAD

**Issue by DevMattDavies** [souvikinator/notion-to-md#80]
Continuation of issue https://github.com/souvikinator/notion-to-md/issues/76

Understand dependency on fs is to be removed in next update.

**Comment by souvikinator** [comment]
Removed `fs` module dependency and will be live in the upcoming release. 
However, you may want to investigate the previous issue you encountered (`fs` should function within `getStaticProp`), as a future update will introduce a feature that requires the `fs ` module.

**Comment by souvikinator** [comment]
This should be fixed in latest version V2.7.0
