### ISSUE TITLE
support notion database

### ISSUE THREAD

**Issue by ghost** [souvikinator/notion-to-md#85]
@souvikinator   👋 I need a Notion database to markdown object format, without converting it to Markdown file. Can you help me?

**Comment by souvikinator** [comment]
Can you be a bit more specific? Markdown file as in markdown string?

**Comment by souvikinator** [comment]
Well notion to md doesn't produce any file. `toMarkdownString` returns object that contains markdown string for the page id you provided. You can pass that string to the react markdown parsing package you'll be using and it should work.
