### ISSUE TITLE
'undefined' in the last line of table markdown string

### ISSUE THREAD

**Issue by feilvan** [souvikinator/notion-to-md#86]
Hello, I got this extra line when I'm trying to convert a table to md string

```
'\n' +
'| Table | Name |\n' +
'| ----- | ---- |\n' +
'| 1     | Aa   |\n' +
'| 2     | Bb   |\n' +
'\n' +
'undefined'
```

The block in Notion looks like this

![image](https://github.com/souvikinator/notion-to-md/assets/73324192/3db1355b-756a-46e5-8cf7-6203930520ba)

Here's the md block (if needed)

```
{
  type: 'table',
  blockId: 'a50e6d08-ffee-428b-b0bd-fc464bb67e88',
  parent: '| Table | Name |\n| ----- | ---- |\n| 1     | Aa   |\n| 2     | Bb   |',
  children: [
    {
      type: 'table_row',
      blockId: 'bcce0040-dfb3-4328-af92-fae1eedcf393',
      parent: '',
      children: []
    },
    {
      type: 'table_row',
      blockId: '4e2cfa23-b872-4a88-8bd7-383e63c7879b',
      parent: '',
      children: []
    },
    {
      type: 'table_row',
      blockId: 'af86e7dd-77a4-4fa1-8123-dce55f1d164f',
      parent: '',
      children: []
    }
  ]
}
```

**Comment by souvikinator** [comment]
Seems like a bug. I'll fix it ASAP.

**Comment by souvikinator** [comment]
This is fixed now. Should be live in the coming update. Thank you for the contribution and using the library.

**Comment by feilvan** [comment]
awesome! thanks for your hard work. this library is perfect for my need.

**Comment by souvikinator** [comment]
Glad to hear that!  Thank you :))
The fix is now live in v3.0.1
Closing the issue, feel free to reopen if the issue still persists.

**Comment by ge9** [comment]
This happened again in 3.1.0.
I think we may need some code for `case "table_row"` near https://github.com/souvikinator/notion-to-md/blob/ffc51450e17f8ebe9f66fdba5babcbc125e925d1/src/notion-to-md.ts#L391.

**Comment by souvikinator** [comment]
I'm on it. I'll fix it and release a patch.
