### ISSUE TITLE
missing/insufficient newlines after <details> tags

### ISSUE THREAD

**Issue by ge9** [souvikinator/notion-to-md#91]
input:
![image](https://github.com/souvikinator/notion-to-md/assets/37699433/1c660144-ccc3-4f1d-8016-46a1fed718e9)
output:
```
<details>
  <summary>summary1</summary>


detail1



  </details>- bullet1
	- bullet2

(some text)

<details>
  <summary>summary2</summary>


detail2



  </details>
### heading3


```
(At least in VS Code preview or Github preview) bullet list (`- xxx`) and headings (`### xxx`) seem to require at least two newlines before them, but in the above output, there are no newlines and only one newline, respectively.

**Comment by souvikinator** [comment]
Thanks for reporting the issue. I'll get into and it should be live in the upcoming release.
