### ISSUE TITLE
Commit to semantic versioning?

### ISSUE THREAD

**Issue by hatton** [souvikinator/notion-to-md#92]
I woke up to our site full of `[object Object]`.  Finally traced it to this change in notion-to-md:

> [V2.7.0](https://github.com/souvikinator/notion-to-md/releases/tag/v2.7.0)
Breaking Changes

> toMarkdownString no longer returns a markdown string, instead returns an object of markdown strings for different pages (child pages) (refer: https://github.com/souvikinator/notion-to-md/blob/master/README.md#separate-child-page-content)

Would you be able to commit to [semantic versioning](https://semver.org/), going forward? It would be a big help.

> MAJOR version when you make incompatible API changes
> MINOR version when you add functionality in a backward compatible manner
> PATCH version when you make backward compatible bug fixes

thanks!

**Comment by souvikinator** [comment]
Apologies for the inconveniences caused. After being reported the same  a while ago I'm trying to get used to the semantic versioning. Hopefully it won't be an issue moving forward.
