### ISSUE TITLE
Wrong typings - CustomTransformer?

### ISSUE THREAD

**Issue by UgRoss** [souvikinator/notion-to-md#93]
Hey 👋

Thank you for creating this library!

I think I've faced a small issue. When I'm trying to return `false` inside a transformer function of the `setCustomTransformer` method, I'm getting the following TS error:

> Argument of type '(block: ListBlockChildrenResponseResult) => boolean' is not assignable to parameter of type 'CustomTransformer'.
  Type 'boolean' is not assignable to type 'string | Promise<string>'.

However, this is what we have in README:

<img width="888" alt="Screenshot 2023-07-05 at 22 48 54" src="https://github.com/souvikinator/notion-to-md/assets/5703885/7a98e095-aee5-458c-bde8-eefaf096d35d">

is there an issue with typings or maybe README is outdated?

**Comment by souvikinator** [comment]
Hey there!
Thanks for the issue I'll look into the PR and merge it.

**Comment by souvikinator** [comment]
Hello! This issue has been fixed and is live in v3.1.1
Thank you for your contribution and for using the package.
Closing the issue. If the problem still persists, feel free to reopen the issue.

**Comment by UgRoss** [comment]
> Hello! This issue has been fixed and is live in v3.1.1 Thank you for your contribution and for using the package. Closing the issue. If the problem still persists, feel free to reopen the issue.

Great, thank you!
